package model;
// Generated 11-may-2016 12:59:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer id;
     private Country country;
     private String name;
     private String district;
     private int population;
     private Set direccioneses = new HashSet(0);

    public City() {
    }

	
    public City(Country country, String name, String district, int population) {
        this.country = country;
        this.name = name;
        this.district = district;
        this.population = population;
    }
    public City(Country country, String name, String district, int population, Set direccioneses) {
       this.country = country;
       this.name = name;
       this.district = district;
       this.population = population;
       this.direccioneses = direccioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public int getPopulation() {
        return this.population;
    }
    
    public void setPopulation(int population) {
        this.population = population;
    }
    public Set getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set direccioneses) {
        this.direccioneses = direccioneses;
    }




}


