package model;
// Generated 11-may-2016 12:59:30 by Hibernate Tools 4.3.1



/**
 * ComentariosLikesId generated by hbm2java
 */
public class ComentariosLikesId  implements java.io.Serializable {


     private int idUsuario;
     private int idComentario;

    public ComentariosLikesId() {
    }

    public ComentariosLikesId(int idUsuario, int idComentario) {
       this.idUsuario = idUsuario;
       this.idComentario = idComentario;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(int idComentario) {
        this.idComentario = idComentario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComentariosLikesId) ) return false;
		 ComentariosLikesId castOther = ( ComentariosLikesId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getIdComentario()==castOther.getIdComentario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getIdComentario();
         return result;
   }   


}


