package model;
// Generated 11-may-2016 12:59:30 by Hibernate Tools 4.3.1

import org.codehaus.jackson.annotate.JsonIgnoreProperties;




/**
 * CountryLanguage generated by hbm2java
 */
@JsonIgnoreProperties(value = {"id"})
public class CountryLanguage  implements java.io.Serializable {


     private CountryLanguageId id;
     private Country country;
     private String isOfficial;

    public CountryLanguage() {
    }

    public CountryLanguage(CountryLanguageId id, Country country, String isOfficial) {
       this.id = id;
       this.country = country;
       this.isOfficial = isOfficial;
    }
   
    public CountryLanguageId getId() {
        return this.id;
    }
    
    public void setId(CountryLanguageId id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getIsOfficial() {
        return this.isOfficial;
    }
    
    public void setIsOfficial(String isOfficial) {
        this.isOfficial = isOfficial;
    }




}


