package model;
// Generated 11-may-2016 12:59:30 by Hibernate Tools 4.3.1



/**
 * CountryLanguageId generated by hbm2java
 */
public class CountryLanguageId  implements java.io.Serializable {


     private String countryCode;
     private String language;

    public CountryLanguageId() {
    }

    public CountryLanguageId(String countryCode, String language) {
       this.countryCode = countryCode;
       this.language = language;
    }
   
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CountryLanguageId) ) return false;
		 CountryLanguageId castOther = ( CountryLanguageId ) other; 
         
		 return ( (this.getCountryCode()==castOther.getCountryCode()) || ( this.getCountryCode()!=null && castOther.getCountryCode()!=null && this.getCountryCode().equals(castOther.getCountryCode()) ) )
 && ( (this.getLanguage()==castOther.getLanguage()) || ( this.getLanguage()!=null && castOther.getLanguage()!=null && this.getLanguage().equals(castOther.getLanguage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCountryCode() == null ? 0 : this.getCountryCode().hashCode() );
         result = 37 * result + ( getLanguage() == null ? 0 : this.getLanguage().hashCode() );
         return result;
   }   


}


