package model;
// Generated 21-abr-2016 16:32:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direcciones generated by hbm2java
 */
public class Direcciones  implements java.io.Serializable {


     private Integer id;
     private String calle;
     private String numero;
     private String ciudad;
     private String provincia;
     private String cp;
     private String pais;
     private Set restauranteses = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Direcciones() {
    }

	
    public Direcciones(String ciudad, String provincia, String cp, String pais) {
        this.ciudad = ciudad;
        this.provincia = provincia;
        this.cp = cp;
        this.pais = pais;
    }
    public Direcciones(String calle, String numero, String ciudad, String provincia, String cp, String pais, Set restauranteses, Set usuarioses) {
       this.calle = calle;
       this.numero = numero;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.cp = cp;
       this.pais = pais;
       this.restauranteses = restauranteses;
       this.usuarioses = usuarioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getRestauranteses() {
        return this.restauranteses;
    }
    
    public void setRestauranteses(Set restauranteses) {
        this.restauranteses = restauranteses;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


