package model;
// Generated 11-may-2016 12:59:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Direcciones generated by hbm2java
 */
public class Direcciones implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private City city;
    private String calle;
    private String numero;
    private String poblacion;
    private String cp;
    private Set restauranteses = new HashSet(0);
    private Set usuarioses = new HashSet(0);

    public Direcciones() {
    }

    public Direcciones(City city, String poblacion, String cp) {
        this.city = city;
        this.poblacion = poblacion;
        this.cp = cp;
    }

    public Direcciones(City city, String calle, String numero, String poblacion, String cp) {
        this.city = city;
        this.calle = calle;
        this.numero = numero;
        this.poblacion = poblacion;
        this.cp = cp;
    }

    public Direcciones(City city, String calle, String numero, String poblacion, String cp, Set restauranteses, Set usuarioses) {
        this.city = city;
        this.calle = calle;
        this.numero = numero;
        this.poblacion = poblacion;
        this.cp = cp;
        this.restauranteses = restauranteses;
        this.usuarioses = usuarioses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public String getCalle() {
        return this.calle;
    }

    public void setCalle(String calle) {
        this.calle = calle;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getPoblacion() {
        return this.poblacion;
    }

    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public Set getRestauranteses() {
        return this.restauranteses;
    }

    public void setRestauranteses(Set restauranteses) {
        this.restauranteses = restauranteses;
    }

    public Set getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

}
