package model;
// Generated 13-mar-2016 20:56:27 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Reservas generated by hbm2java
 */
@XmlRootElement(name = "Reservas")
public class Reservas implements java.io.Serializable {

    private ReservasId id;
    private Restaurantes restaurantes;
    private Usuarios usuarios;
    private int numPersonas;
    private Boolean confirmada;

    public Reservas() {
    }

    public Reservas(ReservasId id, Restaurantes restaurantes, Usuarios usuarios, int numPersonas) {
        this.id = id;
        this.restaurantes = restaurantes;
        this.usuarios = usuarios;
        this.numPersonas = numPersonas;
    }

    public Reservas(ReservasId id, Restaurantes restaurantes, Usuarios usuarios, int numPersonas, Boolean confirmada) {
        this.id = id;
        this.restaurantes = restaurantes;
        this.usuarios = usuarios;
        this.numPersonas = numPersonas;
        this.confirmada = confirmada;
    }

    public ReservasId getId() {
        return this.id;
    }

    public void setId(ReservasId id) {
        this.id = id;
    }

    public Restaurantes getRestaurantes() {
        return this.restaurantes;
    }

    public void setRestaurantes(Restaurantes restaurantes) {
        this.restaurantes = restaurantes;
    }

    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    public int getNumPersonas() {
        return this.numPersonas;
    }

    public void setNumPersonas(int numPersonas) {
        this.numPersonas = numPersonas;
    }

    public Boolean getConfirmada() {
        return this.confirmada;
    }

    public void setConfirmada(Boolean confirmada) {
        this.confirmada = confirmada;
    }

}
