package model;
// Generated 13-mar-2016 20:56:27 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * RestaurantesLikesId generated by hbm2java
 */
@XmlRootElement(name = "RestaurantesLikesId")
public class RestaurantesLikesId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int idUsuario;
    private int idRestaurante;

    public RestaurantesLikesId() {
    }

    public RestaurantesLikesId(int idUsuario, int idRestaurante) {
        this.idUsuario = idUsuario;
        this.idRestaurante = idRestaurante;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getIdRestaurante() {
        return this.idRestaurante;
    }

    public void setIdRestaurante(int idRestaurante) {
        this.idRestaurante = idRestaurante;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RestaurantesLikesId)) {
            return false;
        }
        RestaurantesLikesId castOther = (RestaurantesLikesId) other;

        return (this.getIdUsuario() == castOther.getIdUsuario())
                && (this.getIdRestaurante() == castOther.getIdRestaurante());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdUsuario();
        result = 37 * result + this.getIdRestaurante();
        return result;
    }

}
