package model;
// Generated 05-may-2016 12:10:04 by Hibernate Tools 4.3.1



/**
 * RestaurantesLikes generated by hbm2java
 */
public class RestaurantesLikes  implements java.io.Serializable {


     private RestaurantesLikesId id;
     private Restaurantes restaurantes;
     private Usuarios usuarios;
     private boolean like;

    public RestaurantesLikes() {
    }

    public RestaurantesLikes(RestaurantesLikesId id, Restaurantes restaurantes, Usuarios usuarios, boolean like) {
       this.id = id;
       this.restaurantes = restaurantes;
       this.usuarios = usuarios;
       this.like = like;
    }
   
    public RestaurantesLikesId getId() {
        return this.id;
    }
    
    public void setId(RestaurantesLikesId id) {
        this.id = id;
    }
    public Restaurantes getRestaurantes() {
        return this.restaurantes;
    }
    
    public void setRestaurantes(Restaurantes restaurantes) {
        this.restaurantes = restaurantes;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public boolean isLike() {
        return this.like;
    }
    
    public void setLike(boolean like) {
        this.like = like;
    }




}


