package model;
// Generated 03-abr-2016 21:14:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Restaurantes generated by hbm2java
 */
public class Restaurantes  implements java.io.Serializable {


     private Integer id;
     private Direcciones direcciones;
     private RestaurantesTipos restaurantesTipos;
     private Usuarios usuarios;
     private String nombre;
     private String descripcion;
     private String emailCorporativo;
     private Integer plazas;
     private Date horaApertura;
     private Date horaCierre;
     private Integer telefono;
     private Set comentarioses = new HashSet(0);
     private Set restaurantesLikeses = new HashSet(0);
     private Set reservases = new HashSet(0);
     private Set subscripcioneses = new HashSet(0);
     private Set consultases = new HashSet(0);

    public Restaurantes() {
    }

	
    public Restaurantes(Direcciones direcciones, RestaurantesTipos restaurantesTipos, Usuarios usuarios, String nombre) {
        this.direcciones = direcciones;
        this.restaurantesTipos = restaurantesTipos;
        this.usuarios = usuarios;
        this.nombre = nombre;
    }
    public Restaurantes(Direcciones direcciones, RestaurantesTipos restaurantesTipos, Usuarios usuarios, String nombre, String descripcion, String emailCorporativo, Integer plazas, Date horaApertura, Date horaCierre, Integer telefono, Set comentarioses, Set restaurantesLikeses, Set reservases, Set subscripcioneses, Set consultases) {
       this.direcciones = direcciones;
       this.restaurantesTipos = restaurantesTipos;
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.emailCorporativo = emailCorporativo;
       this.plazas = plazas;
       this.horaApertura = horaApertura;
       this.horaCierre = horaCierre;
       this.telefono = telefono;
       this.comentarioses = comentarioses;
       this.restaurantesLikeses = restaurantesLikeses;
       this.reservases = reservases;
       this.subscripcioneses = subscripcioneses;
       this.consultases = consultases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Direcciones getDirecciones() {
        return this.direcciones;
    }
    
    public void setDirecciones(Direcciones direcciones) {
        this.direcciones = direcciones;
    }
    public RestaurantesTipos getRestaurantesTipos() {
        return this.restaurantesTipos;
    }
    
    public void setRestaurantesTipos(RestaurantesTipos restaurantesTipos) {
        this.restaurantesTipos = restaurantesTipos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEmailCorporativo() {
        return this.emailCorporativo;
    }
    
    public void setEmailCorporativo(String emailCorporativo) {
        this.emailCorporativo = emailCorporativo;
    }
    public Integer getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(Integer plazas) {
        this.plazas = plazas;
    }
    public Date getHoraApertura() {
        return this.horaApertura;
    }
    
    public void setHoraApertura(Date horaApertura) {
        this.horaApertura = horaApertura;
    }
    public Date getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(Date horaCierre) {
        this.horaCierre = horaCierre;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Set getComentarioses() {
        return this.comentarioses;
    }
    
    public void setComentarioses(Set comentarioses) {
        this.comentarioses = comentarioses;
    }
    public Set getRestaurantesLikeses() {
        return this.restaurantesLikeses;
    }
    
    public void setRestaurantesLikeses(Set restaurantesLikeses) {
        this.restaurantesLikeses = restaurantesLikeses;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }
    public Set getSubscripcioneses() {
        return this.subscripcioneses;
    }
    
    public void setSubscripcioneses(Set subscripcioneses) {
        this.subscripcioneses = subscripcioneses;
    }
    public Set getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set consultases) {
        this.consultases = consultases;
    }




}


