package model;
// Generated 13-mar-2016 20:56:27 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * RestaurantesTipos generated by hbm2java
 */
@XmlRootElement(name = "RestaurantesTipos")
public class RestaurantesTipos implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int id;
    private String nombre;
    private Set restauranteses = new HashSet(0);

    public RestaurantesTipos() {
    }

    public RestaurantesTipos(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public RestaurantesTipos(int id, String nombre, Set restauranteses) {
        this.id = id;
        this.nombre = nombre;
        this.restauranteses = restauranteses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getRestauranteses() {
        return this.restauranteses;
    }

    public void setRestauranteses(Set restauranteses) {
        this.restauranteses = restauranteses;
    }

}
