package model;
// Generated 05-may-2016 12:10:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RestaurantesTipos generated by hbm2java
 */
public class RestaurantesTipos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set restauranteses = new HashSet(0);

    public RestaurantesTipos() {
    }

	
    public RestaurantesTipos(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public RestaurantesTipos(int id, String nombre, Set restauranteses) {
       this.id = id;
       this.nombre = nombre;
       this.restauranteses = restauranteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRestauranteses() {
        return this.restauranteses;
    }
    
    public void setRestauranteses(Set restauranteses) {
        this.restauranteses = restauranteses;
    }




}


