package model;
// Generated 03-abr-2016 21:14:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RestaurantesTipos generated by hbm2java
 */
public class RestaurantesTipos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set restauranteses = new HashSet(0);

    public RestaurantesTipos() {
    }

	
    public RestaurantesTipos(String nombre) {
        this.nombre = nombre;
    }
    public RestaurantesTipos(String nombre, Set restauranteses) {
       this.nombre = nombre;
       this.restauranteses = restauranteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRestauranteses() {
        return this.restauranteses;
    }
    
    public void setRestauranteses(Set restauranteses) {
        this.restauranteses = restauranteses;
    }




}


