package model;
// Generated 05-may-2016 12:10:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubscripcionesTipos generated by hbm2java
 */
public class SubscripcionesTipos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int dias;
     private float precio;
     private Set subscripcioneses = new HashSet(0);

    public SubscripcionesTipos() {
    }

	
    public SubscripcionesTipos(int id, String nombre, int dias, float precio) {
        this.id = id;
        this.nombre = nombre;
        this.dias = dias;
        this.precio = precio;
    }
    public SubscripcionesTipos(int id, String nombre, int dias, float precio, Set subscripcioneses) {
       this.id = id;
       this.nombre = nombre;
       this.dias = dias;
       this.precio = precio;
       this.subscripcioneses = subscripcioneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getDias() {
        return this.dias;
    }
    
    public void setDias(int dias) {
        this.dias = dias;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getSubscripcioneses() {
        return this.subscripcioneses;
    }
    
    public void setSubscripcioneses(Set subscripcioneses) {
        this.subscripcioneses = subscripcioneses;
    }




}


