package model;
// Generated 13-mar-2016 20:56:27 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * UsuariosTipos generated by hbm2java
 */
@XmlRootElement(name = "UsuariosTipos")
public class UsuariosTipos implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String nombre;
    private Set usuarioses = new HashSet(0);

    public UsuariosTipos() {
    }

    public UsuariosTipos(String nombre) {
        this.nombre = nombre;
    }

    public UsuariosTipos(String nombre, Set usuarioses) {
        this.nombre = nombre;
        this.usuarioses = usuarioses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getUsuarioses() {
        return this.usuarioses;
    }

    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

}
